### ISSUE TITLE
Pragma should be the `solc` version that can parse the input programs

### ISSUE THREAD

**Issue by thanhtoantnt** [smartbugs/smartbugs-curated#9]
We try to compile programs in your dataset using `solc` with the version in the `pragma`. However, there are many cases `solc` fails to compile.

For example: https://github.com/smartbugs/smartbugs-curated/blob/main/dataset/reentrancy/reentrancy_insecure.sol
The syntax `(bool success, ) = msg.sender.call.value(amountToWithdraw)("");` indicates that `solc` should be `0.5` but the `pragma`  here is `^0.4.0`. 

In other cases, we fail to use `solc` to compile input programs with the version in the `pragma`, and the fix is to change the pragma, e.g., from `0.4.0` to `0.4.11`. Technically, it is not wrong since the pragma indicates the solidity is greater or equal to the version in the pragma. However, this creates a hurdle for dynamic tools that use `solc` to parse the programs. These cases expect the tested tool to try all possible `solc` versions until it can parse the program.

Hence, we hope that you can check this issue and update the `pragma` fields in programs such that it is easier for dynamic tools to use `smartbugs` to run experiments.

**Comment by gsalzer** [comment]
@thanhtoantnt Not sure I understand correctly. Do you mean that in cases where the version specified in the pragma is wrong (compilation with a corresponding solc fails), SmartBugs should try other compiler versions until it finds one that succeeds?

**Comment by gsalzer** [comment]
For the example you give, https://github.com/smartbugs/smartbugs-curated/blob/main/dataset/reentrancy/reentrancy_insecure.sol, the pragma is clearly wrong. It needs to be `^0.4.24` or `^0.5.0`. But as said above, this doesn't look like something that SmartBugs can fix.

**Comment by gsalzer** [comment]
@thanhtoantnt Thanks for reporting the issue. I fixed it, together with two other pragmas. Now, it seems, all solidity files compile.
